### PR TITLE
Begin modularizing for multiple board targets

### PR DESCRIPTION
**Pull request by EnJens**
Some minor modifications to allow multiple different board targets.
Not everything is pretty, but it's a start.

### CODE REVIEW

**Comment by osresearch** [comment]
Looks like a good start.  Rather than naming all of the Ikea board specifically (since there are dozens of them) perhaps a more generic `ikea` or perhaps the Silicon Labs names. Although I haven't seen any differences between the Gecko, Draco and Poly4b that require speciailization.

49465344236_b3fe7df15f_c

48837762711_05f9dd3a40_c

**Comment by EnJens** [comment]
@osresearch hm, sure. I only really did it this way because your definitions had different UART pins for the LED driver board and the onoff switch. If that's not relevant, then I'll happily make it one board

**Comment by osresearch** [comment]
The different UART pins are a historical accident -- on first device I took apart (a floalt driver), I soldered to the pins that were close to the SWD pins and muxed thosed to the USART1.  The rest of the devices I used the same pins as the on-off remote (which has labelled `TX` and `RX` pads) since they seem to be free on all of their designs.  I need to go back a resolder the LED driver.

49316336706_e42f67c161_c

**Comment by EnJens** [comment]
@osresearch How's that? :)

**Pull request merged**
