### PR TITLE
Thunderboard Sense 2 preliminary port

### PR DESCRIPTION
**Pull request by EnJens**
Initial port for Siliconlabs Thunderboard Sense 2.
The basics work, but I'm having trouble getting actual data from the radio currently.
It depends on https://github.com/osresearch/micropython/pull/2/files# for modularity stuff

### CODE REVIEW

**Comment by osresearch** [comment]
Glad you were able to get your board to booting!

Should we make the Gecko sdk and emlib+startup a submodule? It might get unweildy with the additional devices.

**Comment by EnJens** [comment]
probably a good idea - it looks like micropython build system has some native support for that with GIT_SUBMODULES and py/mkrules.mk - just need the submodule to live in $ROOT/lib/efm32 I guess

**Comment by osresearch** [comment]
I've just pushed a pretty major change to move all of the external code into `lib/efm32-base`, which is added as a submodule, and removed the `emlib`, `radio`, `gecko_sdk` and `efr32mg1p` directories from the `ports/efm32` tree. https://github.com/osresearch/micropython/commit/8b375bd861d2027b2422132e7db606a91eaa63de

I also resynced with the upstream microptyhon tree.

Hopefully this makes it easier to configure for different boards since we're not tracking those files in our tree anymore.  Ideally we'll just have to change these make vars:

```
# CPU specific configuration
EFM_FAMILY = efr32mg1p
RAIL_FAMILY = efr32xg1x
EFM_DEV = EFR32MG1P132F256GM32
```

**Comment by EnJens** [comment]
This now depends on https://github.com/osresearch/micropython/pull/2/files# (and includes a commit from it)

**Comment by osresearch** [comment]
Looks good to me. Is this ready to merge?

**Review by osresearch — APPROVED** [review]

**Comment by EnJens** [comment]
I think so - I'm still having trouble getting radio to actually pick something up, but I've verified all radio calls succeed.
I think merging now and fixing whatever issue later might be a good idea

**Comment by osresearch** [comment]
I added `BOARD=tbsense2` to the automated builds https://github.com/osresearch/micropython/commit/f17a2efea93ba32e9f0a093bdf11953ea31ccee6

Did you call `Radio.promiscuous(True)`? The address filtering doesn't seem to work, so I only see packets when the radio is in promiscuous mode.

**Comment by EnJens** [comment]
I did (although the default also seems to be promiscuous looking at the ieee802154_config?
I guess there must be *some* difference between efr32mg1p and efr32mg12p, but it's not very clear what is it :/

**Comment by osresearch** [comment]
Oh, right. I think I changed that when setting up the zrepl stuff since the efr32mg1p doesn't support filtering on multipurpose frames and it was the only way to get data received.

There might be a different clock that needs to be turned on for the radio? It seems that there are lots of separate clock domains and I was mostly turning them on until things worked right.

**Comment by EnJens** [comment]
I just verified their demo firmware for bluetooth works correctly, so I can hopefully use that to try and figure out if anything obvious is missing. (along with the openthread code available)

**Comment by osresearch** [comment]
I'm suspicious of the `librail.a` that is coming from `efm32-base`. It seems to have broken TX (but not RX) on the efr32mg1p boards -- issue #4 is tracking this problem.

Linking against the `librail_efr32xg1_release.a` that we were using before the modularization restores the functionality. You might try linking against `rail/TARGET_EFR32_12/librail_efr32xg12_release.a` from an earlier checkout to see if it fixes your RX problem: https://github.com/osresearch/micropython/tree/479663832f9781426dd8fd57dca174a8ed798187/ports/efm32/rail/TARGET_EFR32_12

**Pull request merged**
